This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file F:/Memoire/CodeSavedOnline/New/MasterThesis/paper/SecondVersion/EPL-TFE_CoverPageTemplate.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file EPL-TFE_CoverPageTemplate.acn....done (35 entries accepted, 0 rejected).
Sorting entries....done (190 comparisons).
Generating output file EPL-TFE_CoverPageTemplate.acr....done (28 lines written, 0 warnings).
Output written in EPL-TFE_CoverPageTemplate.acr.
Transcript written in EPL-TFE_CoverPageTemplate.alg.
